name: JNI Libs noise

on:
#  push:
#    paths-ignore:
#     - 'README.md'
#     - 'CHANGELOG.md'
  pull_request:
    paths-ignore:
     - 'README.md'
     - 'CHANGELOG.md'
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

defaults:
  run:
    shell: bash

jobs:

  build-macos-jni-artifact:
    name: JNI Artifact macOS Build
    runs-on: macos-11
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: install deps
        run:  brew install git automake yasm nasm

      - name: build deps
        run:  |
          ls -al
          id
          pwd
          ./circle_scripts/deps_macos_noise.sh

      - name: build jni lib
        run:  |
          ls -al
          id
          pwd
          ./circle_scripts/java_jni_lib_macos_noise.sh

      - name: sha hash of jni lib
        run:  |
          shasum -a 256 /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore_noise.jnilib || echo "ignore"

      - name: Rename artifact for nightly upload
        if: github.ref == 'refs/heads/master'
        run: |
          pwd
          cp -v /Users/runner/ToxAndroidRefImpl/jni-c-toxcore/libjni-c-toxcore_noise.jnilib libjni-c-toxcore_noise.jnilib
      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libjni-c-toxcore_noise.jnilib
          path: libjni-c-toxcore_noise.jnilib
      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "libjni-c-toxcore_noise.jnilib"

  build-linux-jni-artifact:
    name: JNI Artifact Linux Build
    runs-on: ubuntu-20.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: install deps
        run: |
          sudo apt-get update && \
          sudo DEBIAN_FRONTEND=noninteractive \
          apt-get install -y --no-install-recommends \
          ca-certificates \
          openjdk-17-jdk \
          openjdk-17-jdk-headless \
          coreutils autoconf libtool pkg-config \
          yasm

      - name: build deps
        run:  |
          ls -al
          id
          pwd
          ./circle_scripts/deps_linux_noise.sh

      - name: build jni lib
        run:  |
          ls -al
          id
          pwd
          ./circle_scripts/java_jni_lib_linux_noise.sh

      - name: sha hash of jni lib
        run:  |
          sha256sum /home/runner/work/trifa_material/trifa_material/libjni-c-toxcore_noise.so || echo "ignore"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: libjni-c-toxcore_noise.so
          path: libjni-c-toxcore_noise.so
      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "libjni-c-toxcore_noise.so"


  build-windows-jni-artifact:
    name: JNI Artifact Windows Build
    runs-on: ubuntu-22.04
    permissions:
      contents: write
    steps:
      - uses: actions/checkout@v3

      - name: install deps
        run: |
             sudo apt-get update && \
             sudo DEBIAN_FRONTEND=noninteractive \
             apt-get install -y --no-install-recommends \
             ca-certificates \
             yasm \
             openjdk-17-jdk \
             openjdk-17-jdk-headless \
             coreutils autoconf libtool pkg-config \
             gcc-mingw-w64-x86-64 g++-mingw-w64-x86-64 binutils-mingw-w64-x86-64 \
             mingw-w64-tools pkg-config-mingw-w64-x86-64 win-iconv-mingw-w64-dev \
             mingw-w64-x86-64-dev


      - name: build deps
        run:  |
          ls -al
          id
          pwd
          ./circle_scripts/deps_win_noise.sh

      - name: build jni lib
        run:  |
          ls -al
          id
          pwd
          ./circle_scripts/java_jni_lib_win_noise.sh

      - name: sha hash of jni lib
        run:  |
          sha256sum /home/runner/work/trifa_material/trifa_material/jni-c-toxcore_noise.dll || echo "ignore"

      - name: Upload artifact
        uses: actions/upload-artifact@v4
        with:
          name: jni-c-toxcore_noise.dll
          path: jni-c-toxcore_noise.dll
      - name: Upload to nightly release
        uses: ncipollo/release-action@v1
        if: github.ref == 'refs/heads/master'
        with:
          allowUpdates: true
          tag: nightly
          omitBodyDuringUpdate: true
          omitNameDuringUpdate: true
          prerelease: true
          replacesArtifacts: true
          token: ${{ secrets.GITHUB_TOKEN }}
          artifacts: "jni-c-toxcore_noise.dll"

