name: Screens Only MacOS

on:
  workflow_dispatch:
    inputs:
      version:
        description: dummy
        default: dummy

defaults:
  run:
    shell: bash

jobs:
  macos-test:
    runs-on: macos-13
    if: ${{ true }}
    permissions:
      contents: write
    steps:
    - uses: actions/checkout@v6
    - name: install cliclick
      run:  brew install cliclick

    - name: show architecture
      run:  uname -m

    - name: install imagemagick
      run:  brew install imagemagick

    - name: install wget
      run:  brew install wget

    - name: install sendkeys
      run:  brew install socsieng/tap/sendkeys

    - name: macos-version1
      run: sw_vers -productVersion

    - name: macos-version2
      run: system_profiler SPSoftwareDataType

    - name: csrutil-status
      run: csrutil status || exit 0

    - name: notifications_off_01
      run: launchctl unload -w /System/Library/LaunchAgents/com.apple.notificationcenterui.plist || exit 0

    - name: notifications_off_02
      run: killall NotificationCenter || exit 0

    - name: download tester
      shell: bash
      run: |
           curl -L https://github.com/zoff99/java_tox_tester/archive/refs/heads/master.zip -o master.zip
           unzip master.zip
           ls -al java_tox_tester-master/
           java -version
           javac -version

    - name: download jshowarch
      shell: bash
      run: |
           curl -L https://github.com/zoff99/jshowarch/archive/refs/heads/master.zip -o master.zip
           unzip master.zip
           pwd
           ls -al jshowarch-master/
           java -version
           javac -version
           cd jshowarch-master/
           javac jshowarch.java

    - name: startup-app
      run: |
           pwd
           ls -al /Users/runner/
           _HOME_="/Users/runner/"
           /usr/libexec/java_home -v 17
           export JAVA_HOME=$(/usr/libexec/java_home -v17)
           ./gradlew assemble
           cliclick -m verbose m:12,34
           screencapture -T 1 -x -t png /Users/runner/screen01.png &
           screencapture -T 2 -x -t png /Users/runner/screen02.png &
           screencapture -T 3 -x -t png /Users/runner/screen03.png &
           screencapture -T 10 -x -t png /Users/runner/screen04.png &
           screencapture -T 25 -x -t png /Users/runner/screen05.png &
           screencapture -T 50 -x -t png /Users/runner/screen06.png &
           screencapture -T 60 -x -t png /Users/runner/screen07.png &
           screencapture -T 90 -x -t png /Users/runner/screen09.png &
           screencapture -T 110 -x -t png /Users/runner/screen10.png &
           screencapture -T 248 -x -t png /Users/runner/screenshot-macos.png &
           screencapture -T 240 -x -t png /Users/runner/screen12.png &
           screencapture -T 300 -x -t png /Users/runner/screen13.png &
           pwd
           ls -al
           ./gradlew run > trifa.log 2>&1 &
           pwd
           sleep 45
           cliclick -m verbose c:77,124
           sleep 15
           cliclick -m verbose c:139,124
           sleep 20
           cd /Users/runner/work/trifa_material/trifa_material/java_tox_tester-master/
           ./do_compile.sh
           cat /Users/runner/work/trifa_material/trifa_material/trifa.log
           ./do_run.sh $(cat /Users/runner/work/trifa_material/trifa_material/toxid.txt) >/Users/runner/work/trifa_material/trifa_material/tester.log 2>&1 &
           sleep 68
           ls -al /Users/runner/work/trifa_material/trifa_material/
           cat /Users/runner/work/trifa_material/trifa_material/trifa.log
           cliclick -m verbose c:195,347
           sleep 1
           cliclick -m verbose c:745,627
           sleep 1
           cliclick -m verbose c:367,623
           sleep 2
           sendkeys apps
           sendkeys -a "TRIfA" -c ":smile"
           cd /Users/runner/work/trifa_material/trifa_material/jshowarch-master
           java jshowarch 885 76 115 65 24 &
           sleep 90
           cliclick -m verbose c:367,623
           sleep 120
           cat /Users/runner/work/trifa_material/trifa_material/tester.log
           pwd
           ls -al /Users/runner/
           cp -v /Users/runner/screenshot-macos.png /Users/runner/work/trifa_material/trifa_material/screenshot-macos.png

    - name: tweak screenshot
      run: |
           cd /Users/runner/work/trifa_material/trifa_material/
           pwd
           cp -v screenshot-macos.png /Users/runner/screenshot-macos_orig.png
           convert screenshot-macos.png -crop 1176x885+0+0 +repage crop_br.png
           convert screenshot-macos.png -crop 1919x25+1663+0  crop_br2.png
           convert screenshot-macos.png -crop 1560x88+180+993  crop_br3.png
           convert crop_br3.png  -resize 65%  crop_br3small.png
           composite -compose Copy -gravity South crop_br3small.png crop_br.png -alpha set dst.png
           composite -compose Copy -gravity Northeast crop_br2.png dst.png -alpha set dst2.png
           cp -v dst2.png screenshot-macos.png

    - name: upload-screenshots
      uses: actions/upload-artifact@v5
      with:
        name: screenshot-macos
        path: |
          /Users/runner/screen*.png

    - name: Upload to nightly release
      uses: ncipollo/release-action@v1
      if: github.ref == 'refs/heads/master'
      with:
        allowUpdates: true
        tag: nightly
        omitBodyDuringUpdate: true
        omitNameDuringUpdate: true
        prerelease: true
        replacesArtifacts: true
        token: ${{ secrets.GITHUB_TOKEN }}
        artifacts: "screenshot-macos.png"

